# Generated by Django 6.0.6 on 2026-06-28 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitregistrationmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofilemodel'),
        ),
        migrations.AddField(
            model_name='unitregistrationmodel',
            name='units',
            field=models.ManyToManyField(to='academics.unitmodel'),
        ),
    ]
