# Generated by Django 6.0.6 on 2026-06-28 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.PositiveBigIntegerField(default=0)),
                ('attended_classes', models.PositiveBigIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofilemodel')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.unitmodel')),
            ],
        ),
    ]
